### ISSUE TITLE
Question about Protocol 6 step 4

### ISSUE THREAD

**Issue by 1082008** [dominictarr/secret-handshake-paper#5]
In step 3 A creates H:

H = A<sub>p</sub> | Sign<sub>A</sub>(K | B<sub>p</sub> | hash(a · b))

H is linked to this specific handshake via hash(a · b). B can verify this signature because he can reproduce the signed content. In step 4 he replies with his signature on a message containing K, H and finally hash(a · b).

My question is: why does B have to include that last term hash(a · b) in that signed message? hash(a · b) is already in H, so I think it wouldn't be needed to repeat that. So step 4 could be easier:

A ← B: Box<sub>[K | a · b | a · B | A · b]</sub>(Sign<sub>B</sub>(K | H))

Instead of

A ← B: Box<sub>[K | a · b | a · B | A · b]</sub>(Sign<sub>B</sub>(K | H | hash(a · b)))

**Comment by dominictarr** [comment]
B needs to sign _something_ to prove that he got the message, previous message, so he signs the plaintext of A's auth. The signatures always have the format `K | payload | hash(a.b)` so that that signature cannot be reused in any other context.

the paper mentions:
> For Bob to authenticate back to Alice, he could just sign the proof Alice
sent  him,  and  send  it  back. H is  already  cryptographically  linked  to  the preceding passes.  On the other hand, it is easier to persuade ourselves that
signing K mitigates  CPA[9]  than  that A_p is  never  the  application  key  in another protocol.

The construction around signatures is paranoia about CPA - prepending K means it's locked into this protocol version, and hash(a.b) means it's locked into this session. In practice it would still be very secure without this, but my process is "audit driven crypto" - this means to design not for security directly, but for auditability, which is how we know we have security. It's like test driven development - don't code for correctless, code for testability, which is how we know we have correctness.

sometimes this may produce a protocol that is ["belt and suspenders"](https://en.wiktionary.org/wiki/belt_and_suspenders) but if that is just from an extra hash or two, hashes are cheap!

**Comment by 1082008** [comment]
Thanks for the explanation, it is clear for me now!
